In [1]:
sentences = [
    "The sun was setting behind the mountains, painting the sky in shades of orange and pink.",
    "Artificial intelligence is transforming industries by automating complex tasks.",
    "Success comes to those who are willing to work hard and never give up.",
    "Water boils at 100 degrees Celsius under normal atmospheric pressure.",
    "As she opened the old wooden box, a mysterious glow filled the room.",
    "Time is an illusion, yet it dictates every aspect of our lives.",
    "I told my computer I needed a break, and now it won’t stop sending me vacation ads."
]

In [26]:
from transformers import AutoTokenizer, AutoModel
import torch
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-mpnet-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/all-mpnet-base-v2')

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

In [5]:
example_sentence = 'its a sunny morning'
new_tokens =    new_tokens = tokenizer.encode_plus(example_sentence, max_length=512, truncation=True, padding='max_length', return_tensors='pt')
new_tokens 

{'input_ids': tensor([[    0,  2053,  1041, 11563,  2855,     2,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,  

In [6]:
tokens = {'input_ids': [], 'attention_mask': []}

for sentence in sentences:
    new_tokens = tokenizer.encode_plus(sentence, max_length=512, truncation=True, padding='max_length', return_tensors='pt')
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])

tokens['input_ids'] = torch.stack(tokens['input_ids'])
tokens['attention_mask'] = torch.stack(tokens['attention_mask'])


In [9]:
outputs = model(**tokens)
outputs

BaseModelOutputWithPooling(last_hidden_state=tensor([[[ 2.1330e-03,  4.3467e-02, -2.4626e-04,  ...,  2.3634e-02,
           8.8428e-02, -4.4322e-02],
         [-7.2448e-02, -9.1777e-02, -3.2436e-02,  ...,  4.8388e-02,
           1.8409e-01, -2.5963e-02],
         [-8.9624e-02,  3.9373e-02,  1.7001e-02,  ...,  5.1580e-02,
           1.1998e-01,  1.0614e-02],
         ...,
         [ 1.9111e-02,  1.1562e-01, -4.9137e-02,  ...,  6.7581e-02,
           5.8653e-02,  2.5139e-02],
         [ 1.9111e-02,  1.1562e-01, -4.9137e-02,  ...,  6.7581e-02,
           5.8653e-02,  2.5139e-02],
         [ 1.9111e-02,  1.1562e-01, -4.9137e-02,  ...,  6.7581e-02,
           5.8653e-02,  2.5139e-02]],

        [[-1.6499e-01,  2.3200e-03, -1.1128e-01,  ..., -3.8634e-03,
          -9.9554e-02, -1.2559e-01],
         [-2.3507e-01,  2.4888e-01, -2.2340e-01,  ...,  5.7779e-02,
          -1.4258e-01, -8.7547e-02],
         [-1.2114e-01,  3.9920e-01, -1.8274e-01,  ..., -3.9520e-03,
          -1.7354e-01, -1.2680e

In [10]:
outputs.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [13]:
embeddings = outputs.last_hidden_state
embeddings

tensor([[[ 2.1330e-03,  4.3467e-02, -2.4626e-04,  ...,  2.3634e-02,
           8.8428e-02, -4.4322e-02],
         [-7.2448e-02, -9.1777e-02, -3.2436e-02,  ...,  4.8388e-02,
           1.8409e-01, -2.5963e-02],
         [-8.9624e-02,  3.9373e-02,  1.7001e-02,  ...,  5.1580e-02,
           1.1998e-01,  1.0614e-02],
         ...,
         [ 1.9111e-02,  1.1562e-01, -4.9137e-02,  ...,  6.7581e-02,
           5.8653e-02,  2.5139e-02],
         [ 1.9111e-02,  1.1562e-01, -4.9137e-02,  ...,  6.7581e-02,
           5.8653e-02,  2.5139e-02],
         [ 1.9111e-02,  1.1562e-01, -4.9137e-02,  ...,  6.7581e-02,
           5.8653e-02,  2.5139e-02]],

        [[-1.6499e-01,  2.3200e-03, -1.1128e-01,  ..., -3.8634e-03,
          -9.9554e-02, -1.2559e-01],
         [-2.3507e-01,  2.4888e-01, -2.2340e-01,  ...,  5.7779e-02,
          -1.4258e-01, -8.7547e-02],
         [-1.2114e-01,  3.9920e-01, -1.8274e-01,  ..., -3.9520e-03,
          -1.7354e-01, -1.2680e-01],
         ...,
         [-8.8651e-02,  1

In [14]:
embeddings.shape

torch.Size([7, 512, 768])

# basic concept behind pooling

In [16]:
attention_mask = tokens['attention_mask']
attention_mask.shape

torch.Size([7, 512])

In [17]:
resized_attention_mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
resized_attention_mask.shape

torch.Size([7, 512, 768])

In [19]:
masked_embedding = embeddings * resized_attention_mask
masked_embedding.shape
masked_embedding

tensor([[[ 2.1330e-03,  4.3467e-02, -2.4626e-04,  ...,  2.3634e-02,
           8.8428e-02, -4.4322e-02],
         [-7.2448e-02, -9.1777e-02, -3.2436e-02,  ...,  4.8388e-02,
           1.8409e-01, -2.5963e-02],
         [-8.9624e-02,  3.9373e-02,  1.7001e-02,  ...,  5.1580e-02,
           1.1998e-01,  1.0614e-02],
         ...,
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00]],

        [[-1.6499e-01,  2.3200e-03, -1.1128e-01,  ..., -3.8634e-03,
          -9.9554e-02, -1.2559e-01],
         [-2.3507e-01,  2.4888e-01, -2.2340e-01,  ...,  5.7779e-02,
          -1.4258e-01, -8.7547e-02],
         [-1.2114e-01,  3.9920e-01, -1.8274e-01,  ..., -3.9520e-03,
          -1.7354e-01, -1.2680e-01],
         ...,
         [-0.0000e+00,  0

In [20]:
summed_mask_embeddings = torch.sum(masked_embedding, 1)
summed_mask_embeddings

tensor([[-0.8219, -0.7590, -0.1556,  ...,  0.7899,  2.1785, -0.0442],
        [-1.1174,  2.5114, -2.6329,  ...,  0.6614, -1.7199, -1.3346],
        [ 0.8112,  3.9957, -0.9098,  ..., -0.3844,  3.3705, -2.4583],
        ...,
        [ 2.7252, -0.8334,  0.0582,  ...,  1.1797, -1.0109,  0.0286],
        [ 1.5115,  2.9006, -1.2105,  ...,  0.6317,  2.6627, -0.9313],
        [ 0.2614,  5.4016, -2.2521,  ...,  2.5155, -1.9161, -0.1234]],
       grad_fn=<SumBackward1>)

In [22]:
count_of_one_in_mask_tensor = torch.clamp(resized_attention_mask.sum(1), min=1e-9)
count_of_one_in_mask_tensor


tensor([[20., 20., 20.,  ..., 20., 20., 20.],
        [14., 14., 14.,  ..., 14., 14., 14.],
        [17., 17., 17.,  ..., 17., 17., 17.],
        ...,
        [17., 17., 17.,  ..., 17., 17., 17.],
        [18., 18., 18.,  ..., 18., 18., 18.],
        [23., 23., 23.,  ..., 23., 23., 23.]])

In [25]:
print(summed_mask_embeddings.shape)
print(count_of_one_in_mask_tensor.shape)

torch.Size([7, 768])
torch.Size([7, 768])


In [23]:
mean_pooled = summed_mask_embeddings / count_of_one_in_mask_tensor

In [24]:
mean_pooled.shape

torch.Size([7, 768])

# calculate cosine similarity for sentence 0:

In [27]:
mean_pooled = mean_pooled.detach().numpy()
cosine_similarity([mean_pooled[0]], mean_pooled[1:])

array([[ 0.01878126,  0.03184425,  0.06315354,  0.24879582,  0.11225773,
        -0.00982075]], dtype=float32)